name       : simple-scan
version    : 3.3.92
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/simple-scan/3.3/simple-scan-3.3.92.tar.xz : 01bcf323855df6e4c4ecd098810f8e50d5dd3ad021840b3ef1b80bc977fb77b3
license    : GPL-3.0
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(sane-backends)
    - pkgconfig(colord)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %configure
build      : |
    make -j1
install    : |
    %make_install
