name       : simple-scan
version    : 3.24.1
release    : 5
source     :
    - https://launchpad.net/simple-scan/3.24/3.24.1/+download/simple-scan-3.24.1.tar.xz : 5eae832b14664183d55aa599801cf32f19ff2174dfba4e3d7e4eb4d55810efb3
license    : GPL-3.0
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %configure
build      : |
    make -j1
install    : |
    %make_install
