name       : simple-scan
version    : 3.36.3
release    : 21
source     :
    - https://download.gnome.org/sources/simple-scan/3.36/simple-scan-3.36.3.tar.xz : 7083beab8cb8640225938cda76190abca91093d6960d555505b23930b13c5f3f
license    : GPL-3.0-or-later
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwebp)
    - pkgconfig(gusb)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
