name       : simple-scan
version    : 3.26.2
release    : 7
source     :
    - https://download.gnome.org/sources/simple-scan/3.26/simple-scan-3.26.2.tar.xz : d172825b1b77e2e32c21fc847fd670c4711a504b09688f8567a98ac9516fe212
license    : GPL-3.0
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
