name       : simple-scan
version    : 3.34.2
release    : 13
source     :
    - https://download.gnome.org/sources/simple-scan/3.34/simple-scan-3.34.2.tar.xz : 57f709d6870b1f6d0170ed3fda0087118716b0ccd29c52b9c393519d1c7963ba
license    : GPL-3.0-or-later
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwebp)
    - pkgconfig(gusb)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
