name       : simple-scan
version    : '44.0'
release    : 32
source     :
    - https://download.gnome.org/sources/simple-scan/44/simple-scan-44.0.tar.xz : 39b870fd46f447f747eaecc2df26049ef773185099f0e13c675656264dd98e95
license    : GPL-3.0-or-later
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libwebp)
    - pkgconfig(gusb)
    - pkgconfig(sane-backends)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
