name       : simple-scan
version    : 3.20.0
release    : 3
source     :
    - https://launchpad.net/simple-scan/3.20/3.20.0/+download/simple-scan-3.20.0.tar.xz : 8df5a5a5b06220e98770f11c53db8fc5d0d8d675d1c395f2bcd19fc8656eb62c
license    : GPL-3.0
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(sane-backends)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(colord)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %configure
build      : |
    make -j1
install    : |
    %make_install
