name       : simple-scan
version    : 3.34.1
release    : 12
source     :
    - https://download.gnome.org/sources/simple-scan/3.34/simple-scan-3.34.1.tar.xz : d827fec3383a565724136b6fda543a94c8f8f161782ac6edf9e91ed6fad49f3e
license    : GPL-3.0-or-later
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwebp)
    - pkgconfig(gusb)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
