name       : simple-scan
version    : '40.1'
release    : 25
source     :
    - https://download.gnome.org/sources/simple-scan/40/simple-scan-40.1.tar.xz : ebee39ab1fe4ca053c4ed2bd3a3ca76742ff109436dd0645d3415622132ba0b4
license    : GPL-3.0-or-later
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwebp)
    - pkgconfig(gusb)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-app-window-Make-preferences-modal.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
