name       : simple-scan
version    : 3.26.3
release    : 8
source     :
    - https://download.gnome.org/sources/simple-scan/3.26/simple-scan-3.26.3.tar.xz : c392131e1a975a8c0d9b67132ff7f4044e002935c1f2ed4c00174873189b543d
license    : GPL-3.0
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
