name       : simple-scan
version    : 3.24.0
release    : 4
source     :
    - https://launchpad.net/simple-scan/3.24/3.24.0/+download/simple-scan-3.24.0.tar.xz : 22a44ecfb28b5963f896f1d9f42e789e711f0c1aa9a73fa3c1d74ebb6ca374a6
license    : GPL-3.0
component  : office
summary    : Simple Scanner Utility
description: |
    This is the source code to "Simple Scan" a simple GNOME scanning application, using the sane scanning libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(colord)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gusb)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(sane-backends)
    - libjpeg-turbo-devel
    - itstool
    - vala
setup      : |
    %configure
build      : |
    make -j1
install    : |
    %make_install
